"""empty message

Revision ID: 0f08aee70eaa
Revises: 3b8a6ed35c7c
Create Date: 2021-03-15 23:58:33.254150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f08aee70eaa'
down_revision = '3b8a6ed35c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('previous_help', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'previous_help')
    # ### end Alembic commands ###
