"""empty message

Revision ID: 2faf6b46d966
Revises: 9f321be74c2f
Create Date: 2021-03-01 00:07:50.534516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2faf6b46d966'
down_revision = '9f321be74c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(length=15), nullable=False))
    op.drop_index('phone_numbrer', table_name='user')
    op.create_unique_constraint(None, 'user', ['phone_number'])
    op.drop_column('user', 'phone_numbrer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_numbrer', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('phone_numbrer', 'user', ['phone_numbrer'], unique=True)
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
