"""empty message

Revision ID: 37b501c77f4c
Revises: a7236508a4b4
Create Date: 2021-03-24 23:21:52.813374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37b501c77f4c'
down_revision = 'a7236508a4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='lesson')
    op.alter_column('therapist', 'phobia',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('therapist', 'zipcode',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('therapist', 'zipcode',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('therapist', 'phobia',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.create_index('name', 'lesson', ['name'], unique=True)
    # ### end Alembic commands ###
