"""empty message

Revision ID: 39d6f87d1db2
Revises: 6ac6867557a5
Create Date: 2021-03-04 00:12:46.423012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39d6f87d1db2'
down_revision = '6ac6867557a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patien_phobia',
    sa.Column('id_phobia_lesson', sa.Integer(), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('question_2', sa.Integer(), nullable=True),
    sa.Column('question_4', sa.Integer(), nullable=True),
    sa.Column('question_5', sa.Integer(), nullable=True),
    sa.Column('actual_step', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_phobia_lesson')
    )
    op.create_table('testimonial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('desciption', sa.String(length=300), nullable=True),
    sa.Column('testimonial_photo', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('patient', 'previous_help',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('patient', 'wishfearLESS',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
    op.alter_column('patient', 'zc',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'zc',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('patient', 'wishfearLESS',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
    op.alter_column('patient', 'previous_help',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_table('testimonial')
    op.drop_table('patien_phobia')
    # ### end Alembic commands ###
