"""empty message

Revision ID: 55d3ac83a1f0
Revises: c59b27db2924
Create Date: 2021-03-06 01:39:51.063628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55d3ac83a1f0'
down_revision = 'c59b27db2924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_lesson', sa.Integer(), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=True),
    sa.Column('question_2', sa.Integer(), nullable=True),
    sa.Column('actual_step', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_lesson'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['id_patient'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['question_2'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('patient_phobia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_phobia',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_lesson', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_patient', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_step', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_lesson'], ['lesson.id'], name='patient_phobia_ibfk_1'),
    sa.ForeignKeyConstraint(['id_patient'], ['patient.id'], name='patient_phobia_ibfk_2'),
    sa.ForeignKeyConstraint(['question_2'], ['question.id'], name='patient_phobia_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('patient_lesson')
    # ### end Alembic commands ###
