"""empty message

Revision ID: 5bdb603fec63
Revises: 2faf6b46d966
Create Date: 2021-03-03 20:05:44.210064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdb603fec63'
down_revision = '2faf6b46d966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wishfearLESS', sa.String(length=300), nullable=False),
    sa.Column('previous_help', sa.Boolean(), nullable=False),
    sa.Column('zc', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('therapist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ofice_location', sa.String(length=30), nullable=False),
    sa.Column('experience', sa.String(length=300), nullable=False),
    sa.Column('languages_spoke', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('languages_spoke')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('therapist')
    op.drop_table('patient')
    # ### end Alembic commands ###
