"""empty message

Revision ID: 6ac6867557a5
Revises: 5bdb603fec63
Create Date: 2021-03-03 21:39:30.255473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac6867557a5'
down_revision = '5bdb603fec63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('languages_spoke', table_name='therapist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('languages_spoke', 'therapist', ['languages_spoke'], unique=True)
    # ### end Alembic commands ###
