"""empty message

Revision ID: 7fd63e303772
Revises: f323b288f6da
Create Date: 2021-03-15 23:48:28.709922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fd63e303772'
down_revision = 'f323b288f6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=10), nullable=False))
    op.drop_column('user', 'fisrt_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fisrt_name', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
