"""empty message

Revision ID: 873aefd1b879
Revises: d85d17948679
Create Date: 2021-03-16 00:10:48.869180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873aefd1b879'
down_revision = 'd85d17948679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('severity', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'severity')
    # ### end Alembic commands ###
