"""empty message

Revision ID: 94dab47dc91b
Revises: 9598f49d7d10
Create Date: 2021-03-17 23:08:48.628342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94dab47dc91b'
down_revision = '9598f49d7d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_type', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account_type')
    # ### end Alembic commands ###
