"""empty message

Revision ID: 9598f49d7d10
Revises: 873aefd1b879
Create Date: 2021-03-16 00:56:42.349321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9598f49d7d10'
down_revision = '873aefd1b879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_type', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
