"""empty message

Revision ID: d85d17948679
Revises: 0f08aee70eaa
Create Date: 2021-03-16 00:10:04.648330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd85d17948679'
down_revision = '0f08aee70eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'severity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('severity', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
