"""empty message

Revision ID: f323b288f6da
Revises: 1b506e9349ea
Create Date: 2021-03-15 22:22:06.550746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f323b288f6da'
down_revision = '1b506e9349ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('wishfearless', sa.String(length=300), nullable=True))
    op.drop_column('patient', 'wishfear_less')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('wishfear_less', mysql.VARCHAR(length=300), nullable=True))
    op.drop_column('patient', 'wishfearless')
    # ### end Alembic commands ###
