"""empty message

Revision ID: fb8f6ab7c541
Revises: 94dab47dc91b
Create Date: 2021-03-17 23:52:53.543098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb8f6ab7c541'
down_revision = '94dab47dc91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapist', 'languages_spoke')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapist', sa.Column('languages_spoke', mysql.VARCHAR(length=300), nullable=False))
    # ### end Alembic commands ###
